@extends('layouts.app')

@section('title', 'Game Puzzle - ' . config('app.name'))
@section('meta_description', 'Mainkan game puzzle seru di AlcaOfficial. Asah otak dan nikmati permainan puzzle yang menantang.')
@section('canonical_url', config('app.url') . '/game-puzzle')

@section('content')
<div class="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-pink-50 dark:from-gray-900 dark:via-purple-900 dark:to-gray-900">
    <!-- Header -->
    <div class="container mx-auto px-4 py-8">
        <div class="text-center mb-8">
            <h1 class="text-4xl md:text-5xl font-bold text-gray-800 dark:text-white mb-4">
                🧩 Game Puzzle
            </h1>
            <p class="text-lg text-gray-600 dark:text-gray-300">
                Susun puzzle dan asah otakmu!
            </p>
        </div>
    </div>

    <!-- Game Container -->
    <div class="container mx-auto px-4 pb-12">
        <div class="max-w-2xl mx-auto">
            <!-- Game Stats -->
            <div class="flex justify-between items-center mb-6 bg-white dark:bg-gray-800 rounded-xl p-4 shadow-lg">
                <div class="text-center">
                    <p class="text-sm text-gray-500 dark:text-gray-400">Langkah</p>
                    <p id="moveCount" class="text-2xl font-bold text-purple-600 dark:text-purple-400">0</p>
                </div>
                <div class="text-center">
                    <p class="text-sm text-gray-500 dark:text-gray-400">Waktu</p>
                    <p id="timer" class="text-2xl font-bold text-blue-600 dark:text-blue-400">00:00</p>
                </div>
                <div class="text-center">
                    <p class="text-sm text-gray-500 dark:text-gray-400">Skor</p>
                    <p id="score" class="text-2xl font-bold text-green-600 dark:text-green-400">0</p>
                </div>
            </div>

            <!-- Puzzle Board -->
            <div class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-xl mb-6">
                <div id="puzzleBoard" class="grid grid-cols-3 gap-2 aspect-square max-w-md mx-auto">
                    <!-- Puzzle tiles will be generated by JavaScript -->
                </div>
            </div>

            <!-- Controls -->
            <div class="flex flex-wrap justify-center gap-4">
                <button onclick="shufflePuzzle()" class="px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-semibold transition-colors shadow-lg">
                    <i class="fas fa-random mr-2"></i>Acak Puzzle
                </button>
                <button onclick="resetGame()" class="px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white rounded-lg font-semibold transition-colors shadow-lg">
                    <i class="fas fa-redo mr-2"></i>Reset
                </button>
            </div>

            <!-- Difficulty Selection -->
            <div class="mt-6 bg-white dark:bg-gray-800 rounded-xl p-4 shadow-lg">
                <h3 class="text-lg font-semibold text-gray-800 dark:text-white mb-3 text-center">Tingkat Kesulitan</h3>
                <div class="flex justify-center gap-2">
                    <button onclick="setDifficulty(3)" class="difficulty-btn px-4 py-2 rounded-lg bg-green-500 text-white font-semibold transition-colors" data-size="3">Mudah (3x3)</button>
                    <button onclick="setDifficulty(4)" class="difficulty-btn px-4 py-2 rounded-lg bg-gray-300 dark:bg-gray-600 text-gray-700 dark:text-gray-300 font-semibold transition-colors" data-size="4">Sedang (4x4)</button>
                    <button onclick="setDifficulty(5)" class="difficulty-btn px-4 py-2 rounded-lg bg-gray-300 dark:bg-gray-600 text-gray-700 dark:text-gray-300 font-semibold transition-colors" data-size="5">Sulit (5x5)</button>
                </div>
            </div>
        </div>
    </div>
</div>

@push('styles')
<style>
    .puzzle-tile {
        aspect-ratio: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.5rem;
        font-weight: bold;
        border-radius: 0.5rem;
        cursor: pointer;
        transition: all 0.15s ease;
        user-select: none;
    }

    .puzzle-tile:not(.empty):hover {
        transform: scale(0.95);
    }

    .puzzle-tile.empty {
        background: transparent !important;
        cursor: default;
    }

    @keyframes tileMove {
        0% { transform: scale(0.8); opacity: 0.5; }
        100% { transform: scale(1); opacity: 1; }
    }

    .tile-animate {
        animation: tileMove 0.15s ease;
    }
</style>
@endpush

@push('scripts')
<script>
    let gridSize = 3;
    let tiles = [];
    let emptyIndex;
    let moveCount = 0;
    let seconds = 0;
    let timerInterval = null;
    let gameStarted = false;
    let score = 0;

    // Initialize game
    function initGame() {
        createPuzzle();
        shufflePuzzle();
    }

    // Create puzzle tiles
    function createPuzzle() {
        const board = document.getElementById('puzzleBoard');
        board.className = `grid grid-cols-${gridSize} gap-2 aspect-square max-w-md mx-auto`;
        board.innerHTML = '';

        tiles = [];
        for (let i = 1; i < gridSize * gridSize; i++) {
            tiles.push(i);
        }
        tiles.push(0); // Empty tile
        emptyIndex = tiles.length - 1;

        renderBoard();
    }

    // Render the puzzle board
    function renderBoard() {
        const board = document.getElementById('puzzleBoard');
        board.innerHTML = '';

        const colors = [
            'bg-red-400', 'bg-orange-400', 'bg-yellow-400',
            'bg-green-400', 'bg-teal-400', 'bg-blue-400',
            'bg-indigo-400', 'bg-purple-400', 'bg-pink-400'
        ];

        tiles.forEach((tile, index) => {
            const div = document.createElement('div');
            div.className = `puzzle-tile ${tile === 0 ? 'empty' : colors[(tile - 1) % colors.length] + ' text-white shadow-md'}`;
            div.textContent = tile === 0 ? '' : tile;
            div.onclick = () => moveTile(index);

            if (tile !== 0) {
                const row = Math.floor(index / gridSize);
                const col = index % gridSize;
                const emptyRow = Math.floor(emptyIndex / gridSize);
                const emptyCol = emptyIndex % gridSize;

                if ((Math.abs(row - emptyRow) === 1 && col === emptyCol) ||
                    (Math.abs(col - emptyCol) === 1 && row === emptyRow)) {
                    div.classList.add('hover:ring-4', 'hover:ring-white', 'hover:ring-opacity-50');
                }
            }

            board.appendChild(div);
        });
    }

    // Move a tile
    function moveTile(index) {
        const row = Math.floor(index / gridSize);
        const col = index % gridSize;
        const emptyRow = Math.floor(emptyIndex / gridSize);
        const emptyCol = emptyIndex % gridSize;

        const isAdjacent = (Math.abs(row - emptyRow) === 1 && col === emptyCol) ||
                          (Math.abs(col - emptyCol) === 1 && row === emptyRow);

        if (isAdjacent) {
            // Start timer on first move
            if (!gameStarted) {
                gameStarted = true;
                startTimer();
            }

            // Swap tiles
            [tiles[index], tiles[emptyIndex]] = [tiles[emptyIndex], tiles[index]];
            emptyIndex = index;
            moveCount++;

            document.getElementById('moveCount').textContent = moveCount;
            renderBoard();

            // Check for win
            checkWin();
        }
    }

    // Check if puzzle is solved
    function checkWin() {
        for (let i = 0; i < tiles.length - 1; i++) {
            if (tiles[i] !== i + 1) return false;
        }

        // Puzzle solved!
        clearInterval(timerInterval);
        score = Math.max(0, 1000 - moveCount * 5 - seconds);
        document.getElementById('score').textContent = score;

        // Show win message
        setTimeout(() => {
            alert(`🎉 Selamat! Kamu menyelesaikan puzzle dalam ${moveCount} langkah dan ${formatTime(seconds)}! Skor: ${score}`);
        }, 100);

        return true;
    }

    // Shuffle puzzle
    function shufflePuzzle() {
        resetGame();

        // Perform random valid moves to ensure solvability
        for (let i = 0; i < 100; i++) {
            const adjacentTiles = getAdjacentTiles(emptyIndex);
            const randomIndex = adjacentTiles[Math.floor(Math.random() * adjacentTiles.length)];
            [tiles[randomIndex], tiles[emptyIndex]] = [tiles[emptyIndex], tiles[randomIndex]];
            emptyIndex = randomIndex;
        }

        renderBoard();
    }

    // Get adjacent tile indices
    function getAdjacentTiles(index) {
        const row = Math.floor(index / gridSize);
        const col = index % gridSize;
        const adjacent = [];

        if (row > 0) adjacent.push(index - gridSize); // Up
        if (row < gridSize - 1) adjacent.push(index + gridSize); // Down
        if (col > 0) adjacent.push(index - 1); // Left
        if (col < gridSize - 1) adjacent.push(index + 1); // Right

        return adjacent;
    }

    // Reset game
    function resetGame() {
        clearInterval(timerInterval);
        moveCount = 0;
        seconds = 0;
        gameStarted = false;
        score = 0;
        document.getElementById('moveCount').textContent = '0';
        document.getElementById('timer').textContent = '00:00';
        document.getElementById('score').textContent = '0';
    }

    // Set difficulty
    function setDifficulty(size) {
        gridSize = size;

        // Update button styles
        document.querySelectorAll('.difficulty-btn').forEach(btn => {
            if (parseInt(btn.dataset.size) === size) {
                btn.className = 'difficulty-btn px-4 py-2 rounded-lg bg-green-500 text-white font-semibold transition-colors';
            } else {
                btn.className = 'difficulty-btn px-4 py-2 rounded-lg bg-gray-300 dark:bg-gray-600 text-gray-700 dark:text-gray-300 font-semibold transition-colors';
            }
        });

        createPuzzle();
        shufflePuzzle();
    }

    // Timer functions
    function startTimer() {
        timerInterval = setInterval(() => {
            seconds++;
            document.getElementById('timer').textContent = formatTime(seconds);
        }, 1000);
    }

    function formatTime(totalSeconds) {
        const mins = Math.floor(totalSeconds / 60).toString().padStart(2, '0');
        const secs = (totalSeconds % 60).toString().padStart(2, '0');
        return `${mins}:${secs}`;
    }

    // Initialize on load
    document.addEventListener('DOMContentLoaded', initGame);
</script>
@endpush
